# Generated by Django 5.0.14 on 2026-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_apps', '0002_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('time_slot', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('health_tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('quantity_display', models.CharField(max_length=100)),
            ],
        ),
    ]
